# Generated by Django 2.2.24 on 2021-10-29 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_delete_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Рецепт в избранном', 'verbose_name_plural': 'Избранные рецепты'},
        ),
    ]
